Pin pytorch-lightning version to 1.7.7 to fix crash
Attempts to use easy_train.sh crash with this error:

AttributeError: `Trainer.root_gpu` was deprecated in
v1.6 and is no longer accessible as of v1.8. Please use
`Trainer.strategy.root_device.index` instead.

Support for Trainer.root_gpu was removed in:
https://github.com/Lightning-AI/lightning/issues/11994